### ISSUE TITLE
Additional Validation for imported models

### ISSUE THREAD

**Issue by yT0n1** [bptlab/chor-js-demo#17]
Include validation checks for incorrect constructs that would not be possible to model with chor-js but could be imported from other editors. Such as parallel gateways after event based gateways, etc.

**Comment by yT0n1** [comment]
Detect circular dependencies and switch to chor-js diagramWalkerUtil

**Comment by jan-ladleif** [comment]
This could be part of the validator ("structural soundness" or something), but we should not prohibit importing those models.
