### ISSUE TITLE
Keep file name when uploading and downloading

### ISSUE THREAD

**Issue by LeonBein** [bptlab/chor-js-demo#39]
#### Expected behavior: 
As a choreography developer,
when I have created a choreography and named its file
&nbsp;&nbsp;&nbsp;and I upload the file again to adapt some elements
&nbsp;&nbsp;&nbsp;and then download the changed file
I expect it to have its original file name,
so I can paste it back to the folder I uploaded it from and replace the old file

#### Actual behavior: 
The file is simply called 'diagram.bpmn'

**Comment by jan-ladleif** [comment]
Thanks for the suggestion, makes sense! 👍 

Minor caveat: in the current solution, SVGs are now named something like `diagram.bpmn.svg`, but I think that's fine. Did not want to implement a huge string manipulation thing.
