### ISSUE TITLE
Add drag & drop support for loading diagrams

### ISSUE THREAD

**Issue by jffjhnsn** [bptlab/chor-js-demo#49]
Currently, diagrams can only be loaded from the disk via a typical "Open File" dialog. We'd like for users to alternatively be able to drag diagrams (.bpmn files) into the editor and load them.

**Comment by jffjhnsn** [comment]
The [current version](https://github.com/bptlab/chor-js-demo/commit/9e843cc52922126262dae49e689a9a2b8ea3b721) of drag & drop works for me on Windows, but not on Ubuntu. However, I notice the typical "Load file" button doesn't work on Ubuntu either, so it looks to be an issue with how imports are handled.

**Comment by jan-ladleif** [comment]
Closed by #53
